site_name: Django Nitro Mailer Documentation
theme:
  name: material

docs_dir: pages

nav:
  - About the application: about.md
  - Installation: installation.md
  - Sending emails: sending_emails.md
  - Environment variables: environment_variables.md
