site_name: Django Nitro Mailer Documentation
theme:
  name: material

docs_dir: pages

nav:
  - Introduction: index.md
  - Quickstart: quickstart.md
  - Sending emails: sending-emails.md
  - Settings: settings.md
